# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 20  # Hz

    arm_ur5e_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_robotiq_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_ur5e_controller:
  ros__parameters:
    joints:
      - ur5e_shoulder_pan_joint
      - ur5e_shoulder_lift_joint
      - ur5e_elbow_joint
      - ur5e_wrist_1_joint
      - ur5e_wrist_2_joint
      - ur5e_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
gripper_robotiq_controller:
  ros__parameters:
    joint: gripper_finger_joint
